# Generated by Django 5.2.4 on 2025-07-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Accessory Name (e.g., Buttons, Thread Spool, Zipper)",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Button, Thread, Zipper (Optional)",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Quantity in units (e.g., number of buttons, spools, zippers)",
                    ),
                ),
                (
                    "purchase_price_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost price per unit (Optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Accessory",
                "verbose_name_plural": "Accessories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Fabric Name (e.g., Cotton Latha, Boski)",
                        max_length=150,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Color of the fabric", max_length=100
                    ),
                ),
                (
                    "quantity_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Quantity in meters",
                        max_digits=10,
                    ),
                ),
                (
                    "purchase_price_per_meter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost price (Optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Supplier name (Optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fabric",
                "verbose_name_plural": "Fabrics",
                "ordering": ["name", "color"],
                "unique_together": {("name", "color")},
            },
        ),
    ]
