# Generated by Django 5.2.4 on 2025-07-07 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Customer's full name", max_length=100),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Customer's phone number (Unique)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Customer's address (Optional)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_set_name",
                    models.CharField(
                        help_text="e.g., 'For Kameez Shalwar Jan 2023', 'For Sherwani'",
                        max_length=100,
                    ),
                ),
                (
                    "measurement_data",
                    models.JSONField(
                        help_text="Flexible JSON field for various measurements (e.g., {'length': 40, 'chest': 22})"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Set",
                "verbose_name_plural": "Measurement Sets",
                "ordering": ["-created_at"],
            },
        ),
    ]
