# Generated by Django 5.2.4 on 2025-07-07 19:25

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        ("karigars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=orders.models.generate_order_number,
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "order_details",
                    models.TextField(
                        blank=True,
                        help_text="General notes or special instructions for the entire order",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("InProgress", "In Progress"),
                            ("Stitching", "Stitching"),
                            ("Finishing", "Finishing"),
                            ("ReadyForPickup", "Ready for Pickup"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("OnHold", "On Hold"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the order was placed/recorded",
                    ),
                ),
                (
                    "delivery_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Promised delivery date to customer",
                        null=True,
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual date the order was completed/delivered",
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total calculated value of the order (sum of item prices)",
                        max_digits=10,
                    ),
                ),
                (
                    "advance_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Advance amount paid by customer",
                        max_digits=10,
                    ),
                ),
                (
                    "voice_note_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to stored voice note, if any",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "design_image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to stored design image, if any",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_karigar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Karigar primarily responsible for this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_orders",
                        to="karigars.karigar",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer placing the order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="e.g., Kameez, Shalwar, Sherwani, Kurta",
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this single item",
                        max_digits=10,
                    ),
                ),
                (
                    "item_specific_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions specific to this item",
                        null=True,
                    ),
                ),
                (
                    "fabric_quantity_used_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Meters of fabric used for this item (if applicable from inventory)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fabric",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fabric from inventory used for this item (Optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.fabric",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific measurement set for this item (Optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.measurement",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "ordering": ["created_at"],
            },
        ),
    ]
