# Generated by Django 5.2.4 on 2025-07-07 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid in this transaction",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the payment was made/recorded",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("BankTransfer", "Bank Transfer"),
                            ("Easypaisa", "Easypaisa"),
                            ("JazzCash", "JazzCash"),
                            ("Card", "Credit/Debit Card"),
                            ("Other", "Other"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the payment (e.g., transaction ID, partial payment reason)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
