# Generated by Django 5.2.4 on 2025-07-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="design_image_url",
        ),
        migrations.RemoveField(
            model_name="order",
            name="voice_note_url",
        ),
        migrations.AddField(
            model_name="order",
            name="design_image",
            field=models.ImageField(
                blank=True,
                help_text="Image sketch or design for the order",
                null=True,
                upload_to="orders/design_images/",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="voice_note",
            field=models.FileField(
                blank=True,
                help_text="Voice note for order instructions",
                null=True,
                upload_to="orders/voice_notes/",
            ),
        ),
    ]
