# Generated by Django 5.2.4 on 2025-07-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Karigar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Karigar's full name", max_length=100),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Karigar's phone number (Optional, but recommended)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True,
                        help_text="e.g., Shalwar Kameez specialist, Sherwani expert (Optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Karigar (Craftsman)",
                "verbose_name_plural": "Karigars (Craftsmen)",
                "ordering": ["name"],
            },
        ),
    ]
